name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 51.20.31.212
          username: ec2-user
          key: ${{ secrets.test_key }}
          port: 22
          command_timeout: 10m
          script: |
            set -e
          
            cd ~/fullstack
            
            echo "🔧 Fixing permissions..."
            sudo chown -R ec2-user:ec2-user ~/fullstack
            
            echo "📥 Pulling latest code..."
            git pull origin main
            
            echo "🐳 Restarting Docker..."
            docker-compose down || true
            docker-compose up -d --build
            
            echo "✅ Deployment successful!"
